# Generated by Django 5.2.7 on 2025-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bitacora', '0001_clean_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=100)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'etapas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experimentos',
            fields=[
                ('id_experimento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experimento',
                'verbose_name_plural': 'Experimentos',
                'db_table': 'experimentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantas',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(blank=True, max_length=150, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('region_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_planta', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'plantas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hojas', models.IntegerField(blank=True, null=True)),
                ('luz_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'registros',
                'managed': False,
            },
        ),
    ]
